name: Build
on:
  push:
    paths:
      - "afm-demo.bicep"
      - "avmm-demo.bicep"  
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build Demos
    runs-on: ubuntu-latest
    steps:
      - name: Run Bicep Build action for Azure Firewall Manager Demo
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: afm-demo.bicep
      - name: Run Bicep Build action for Azure Virtual Network Manager Demo
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: avnm-demo.bicep
