name: Build
on:
  push:
    branches:
      - master
    paths:
      - ".github/**"
      - "afm/**"
      - "avnm/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_and_test:
    name: Build Demos
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Run Bicep Build action for Azure Firewall Manager Demo
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: ./afm/main.bicep
      - name: Run Bicep Build action for Azure Virtual Network Manager Demo
        uses: Azure/bicep-build-action@v1.0.1
        with:
          bicepFilePath: ./avnm/main.bicep
